# Generated by Django 2.0.5 on 2018-05-17 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(max_length=10)),
                ('finished', models.BooleanField(default=False)),
                ('results_limit_per_athlete', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('criterion_for_best_result', models.CharField(choices=[('min', 'Minimum value'), ('max', 'Maximum value')], default='max', max_length=3)),
            ],
        ),
    ]
