# Generated by Django 2.0.5 on 2018-05-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
